### ISSUE TITLE
Unable To Build Docker Image

### ISSUE THREAD

**Issue by dhruvbaslas** [miniSat/Minisat#180]
After Running This:
docker build -t minisat:latest .

It Says:
Error: Failed to synchronize cache for repo 'updates'

**Comment by khomesh24** [comment]
@dhruvbaslas 
Its working fine for me, can you provide some detail description about how to get this error.

Most probably **Error: Failed to synchronize cache for repo 'updates** occurs due to network connectivity.

**Comment by dhruvbaslas** [comment]
I ran everything in Ubuntu though, it was mentioned Tested on Fedora. I
changed other commands for Ubuntu but as this is in docker, I don't think I
need to change this command.

Can using it in Ubuntu be the problem?
